name: Npm Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build --workspace=@holaplex/ui-library-react
      - uses: JS-DevTools/npm-publish@v1
        working-directory: ./packages/@holaplexui-react
        with:
          token: ${{ secrets.NPM_TOKEN }}